AWSTemplateFormatVersion: "2010-09-09"
Resources:
    SmartGroupConfigurations:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        -
          AttributeName: "jssId"
          AttributeType: "S"
        KeySchema:
        -
          AttributeName: "jssId"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
