AWSTemplateFormatVersion: "2010-09-09"
Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "SmartGroupConfigurations"
        AttributeDefinitions:
        - AttributeName: jssId
          AttributeType: S
        KeySchema:
        - AttributeName: jssId
          KeyType: HASH
        - AttributeName: groupId
          AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
